name: Rustfmt
on: [push, workflow_dispatch]
jobs:
  format_rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/rust
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D warnings
  build_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: build
        run: cargo build 
        working-directory: ./src/rust