name: Rustfmt
on: [push, workflow_dispatch]
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/rust
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: fmt
        run: cargo fmt --all -- --check